version: "3.9"
networks:
  db-net:
    external: true
    driver: "bridge"

services:
  api:
    build: .
    environment:
      DB_HOST: "db"
    ports:
      - "80:8080"
    networks:
      - db-net
    depends_on:
      - db
    image: 'produto-api:${TAG:-latest}'
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ${PG_PASS:?err}
      POSTGRES_DB: 'sample-api'
    networks:
      - db-net
    ports:
      - "5432:5432"
