version: "3.9"
networks:
  db-net: {}
name: "sample-api-2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.1-SNAPSHOT"
      target: runnerComCache
    environment:
      DB_HOST: "db"
      MONGO_URI: "mongodb://root:mongo@nosql-db:27017/sample-api"
    ports:
      - "8080:8080"
    networks:
      - db-net
    depends_on:
      - db
      - nosql-db
    image: 'produto-api:${TAG:-latest}'
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'sample-api'
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    networks:
      - db-net
  nosql-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - db-net
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - nosql-db
    ports:
      - 8081:8081
    networks:
      - db-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@nosql-db:27017/
